"""add cascade delete

Revision ID: 276337b88242
Revises: f47c6422d16b
Create Date: 2026-09-09 22:12:13.190721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276337b88242'
down_revision: Union[str, Sequence[str], None] = 'f47c6422d16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workspace_member_workspace_id_fkey'), 'workspace_member', type_='foreignkey')
    op.drop_constraint(op.f('workspace_member_user_id_fkey'), 'workspace_member', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_member', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_member', type_='foreignkey')
    op.drop_constraint(None, 'workspace_member', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_member_user_id_fkey'), 'workspace_member', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('workspace_member_workspace_id_fkey'), 'workspace_member', 'workspace', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
