"""update document constraints

Revision ID: 50343fadb80a
Revises: 276337b88242
Create Date: 2026-09-15 22:43:50.592786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50343fadb80a'
down_revision: Union[str, Sequence[str], None] = '276337b88242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'external_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1024),
               existing_nullable=True)
    op.drop_constraint(op.f('document_workspace_id_fkey'), 'document', type_='foreignkey')
    op.drop_constraint(op.f('document_source_id_fkey'), 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document', 'source', ['source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_chunk_document_version_id_fkey'), 'document_chunk', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunk', 'document_version', ['document_version_id'], ['id'], ondelete='CASCADE')
    op.alter_column('document_version', 's3_key',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1024),
               existing_nullable=True)
    op.alter_column('document_version', 'mime_type',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('document_version_document_id_fkey'), 'document_version', type_='foreignkey')
    op.create_foreign_key(None, 'document_version', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_version', type_='foreignkey')
    op.create_foreign_key(op.f('document_version_document_id_fkey'), 'document_version', 'document', ['document_id'], ['id'])
    op.alter_column('document_version', 'mime_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('document_version', 's3_key',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1024),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'document_chunk', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunk_document_version_id_fkey'), 'document_chunk', 'document_version', ['document_version_id'], ['id'])
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key(op.f('document_source_id_fkey'), 'document', 'source', ['source_id'], ['id'])
    op.create_foreign_key(op.f('document_workspace_id_fkey'), 'document', 'workspace', ['workspace_id'], ['id'])
    op.alter_column('document', 'external_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1024),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
