"""ingesion model cascade 추가

Revision ID: 89556cfeeca8
Revises: 50343fadb80a
Create Date: 2026-09-17 21:47:39.807260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89556cfeeca8'
down_revision: Union[str, Sequence[str], None] = '50343fadb80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ingestion_job_document_version_id_fkey'), 'ingestion_job', type_='foreignkey')
    op.create_foreign_key(None, 'ingestion_job', 'document_version', ['document_version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingestion_job', type_='foreignkey')
    op.create_foreign_key(op.f('ingestion_job_document_version_id_fkey'), 'ingestion_job', 'document_version', ['document_version_id'], ['id'])
    # ### end Alembic commands ###
